import { Student } from './types';

export const TEACHER_CREDENTIALS = {
  username: 'major',
  password: '123456',
};

// Fix: Explicitly type as number to avoid comparison errors in other files.
// TypeScript was inferring the literal types 16 and 10, which can never be 0.
export const TOTAL_MEETINGS: number = 16;
export const TOTAL_TASKS: number = 10;

export const INITIAL_STUDENTS_DATA: Student[] = [
  {
    id: 1,
    name: 'Budi Santoso',
    nim: '12345',
    picture: 'https://picsum.photos/seed/budi/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 85, final1: 90, mid2: 88, final2: 92 },
    proactiveness: { bertanya: 10, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 2,
    name: 'Citra Lestari',
    nim: '67890',
    picture: 'https://picsum.photos/seed/citra/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 92, final1: 95, mid2: 90, final2: 98 },
    proactiveness: { bertanya: 15, menjawab: 10, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 3,
    name: 'Dewi Anggraini',
    nim: '54321',
    picture: 'https://picsum.photos/seed/dewi/200',
    attendance: { hadir: 12, izin: 2, sakit: 2 },
    exams: { mid1: 78, final1: 80, mid2: 82, final2: 85 },
    proactiveness: { bertanya: 5, menjawab: 3, menambahkan: 1 },
    tasks: { selesai: 8 },
  },
  {
    id: 4,
    name: 'Eko Prasetyo',
    nim: '12346',
    picture: 'https://picsum.photos/seed/eko/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 80, final1: 85, mid2: 82, final2: 88 },
    proactiveness: { bertanya: 8, menjawab: 4, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 5,
    name: 'Fajar Nugroho',
    nim: '12347',
    picture: 'https://picsum.photos/seed/fajar/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 88, final1: 91, mid2: 86, final2: 93 },
    proactiveness: { bertanya: 12, menjawab: 6, menambahkan: 4 },
    tasks: { selesai: 9 },
  },
  {
    id: 6,
    name: 'Gita Puspita',
    nim: '12348',
    picture: 'https://picsum.photos/seed/gita/200',
    attendance: { hadir: 13, izin: 2, sakit: 1 },
    exams: { mid1: 75, final1: 78, mid2: 80, final2: 83 },
    proactiveness: { bertanya: 6, menjawab: 2, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 7,
    name: 'Hadi Wirawan',
    nim: '12349',
    picture: 'https://picsum.photos/seed/hadi/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 95, final1: 97, mid2: 94, final2: 99 },
    proactiveness: { bertanya: 14, menjawab: 9, menambahkan: 6 },
    tasks: { selesai: 10 },
  },
  {
    id: 8,
    name: 'Indah Permatasari',
    nim: '12350',
    picture: 'https://picsum.photos/seed/indah/200',
    attendance: { hadir: 14, izin: 0, sakit: 2 },
    exams: { mid1: 82, final1: 86, mid2: 84, final2: 90 },
    proactiveness: { bertanya: 9, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 9,
    name: 'Joko Susilo',
    nim: '12351',
    picture: 'https://picsum.photos/seed/joko/200',
    attendance: { hadir: 11, izin: 3, sakit: 2 },
    exams: { mid1: 70, final1: 72, mid2: 75, final2: 79 },
    proactiveness: { bertanya: 4, menjawab: 1, menambahkan: 0 },
    tasks: { selesai: 7 },
  },
  {
    id: 10,
    name: 'Kartika Sari',
    nim: '12352',
    picture: 'https://picsum.photos/seed/kartika/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 90, final1: 93, mid2: 89, final2: 96 },
    proactiveness: { bertanya: 13, menjawab: 8, menambahkan: 4 },
    tasks: { selesai: 10 },
  },
  {
    id: 11,
    name: 'Lila Wulandari',
    nim: '12353',
    picture: 'https://picsum.photos/seed/lila/200',
    attendance: { hadir: 13, izin: 1, sakit: 2 },
    exams: { mid1: 79, final1: 81, mid2: 83, final2: 87 },
    proactiveness: { bertanya: 7, menjawab: 3, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 12,
    name: 'Maulana Yusuf',
    nim: '12354',
    picture: 'https://picsum.photos/seed/maulana/200',
    attendance: { hadir: 12, izin: 2, sakit: 2 },
    exams: { mid1: 72, final1: 75, mid2: 77, final2: 80 },
    proactiveness: { bertanya: 5, menjawab: 2, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 13,
    name: 'Nina Agustina',
    nim: '12355',
    picture: 'https://picsum.photos/seed/nina/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 98, final1: 100, mid2: 97, final2: 100 },
    proactiveness: { bertanya: 16, menjawab: 12, menambahkan: 8 },
    tasks: { selesai: 10 },
  },
  {
    id: 14,
    name: 'Omar Syarif',
    nim: '12356',
    picture: 'https://picsum.photos/seed/omar/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 83, final1: 87, mid2: 85, final2: 91 },
    proactiveness: { bertanya: 10, menjawab: 6, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 15,
    name: 'Putri Handayani',
    nim: '12357',
    picture: 'https://picsum.photos/seed/putri/200',
    attendance: { hadir: 15, izin: 0, sakit: 1 },
    exams: { mid1: 89, final1: 92, mid2: 90, final2: 95 },
    proactiveness: { bertanya: 11, menjawab: 7, menambahkan: 4 },
    tasks: { selesai: 9 },
  },
  {
    id: 16,
    name: 'Qori Ramadhan',
    nim: '12358',
    picture: 'https://picsum.photos/seed/qori/200',
    attendance: { hadir: 13, izin: 2, sakit: 1 },
    exams: { mid1: 77, final1: 80, mid2: 79, final2: 84 },
    proactiveness: { bertanya: 6, menjawab: 3, menambahkan: 1 },
    tasks: { selesai: 8 },
  },
  {
    id: 17,
    name: 'Rizky Amelia',
    nim: '12359',
    picture: 'https://picsum.photos/seed/rizky/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 84, final1: 88, mid2: 86, final2: 92 },
    proactiveness: { bertanya: 10, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 18,
    name: 'Surya Pratama',
    nim: '12360',
    picture: 'https://picsum.photos/seed/surya/200',
    attendance: { hadir: 12, izin: 3, sakit: 1 },
    exams: { mid1: 74, final1: 77, mid2: 76, final2: 81 },
    proactiveness: { bertanya: 5, menjawab: 2, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 19,
    name: 'Tika Novitasari',
    nim: '12361',
    picture: 'https://picsum.photos/seed/tika/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 91, final1: 94, mid2: 92, final2: 97 },
    proactiveness: { bertanya: 13, menjawab: 8, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 20,
    name: 'Umar Faruq',
    nim: '12362',
    picture: 'https://picsum.photos/seed/umar/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 96, final1: 98, mid2: 95, final2: 100 },
    proactiveness: { bertanya: 15, menjawab: 10, menambahkan: 7 },
    tasks: { selesai: 10 },
  },
  {
    id: 21,
    name: 'Vina Rahmawati',
    nim: '12363',
    picture: 'https://picsum.photos/seed/vina/200',
    attendance: { hadir: 14, izin: 2, sakit: 0 },
    exams: { mid1: 81, final1: 84, mid2: 82, final2: 88 },
    proactiveness: { bertanya: 8, menjawab: 4, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 22,
    name: 'Wahyu Hidayat',
    nim: '12364',
    picture: 'https://picsum.photos/seed/wahyu/200',
    attendance: { hadir: 13, izin: 1, sakit: 2 },
    exams: { mid1: 76, final1: 79, mid2: 78, final2: 82 },
    proactiveness: { bertanya: 7, menjawab: 3, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 23,
    name: 'Xena Maulina',
    nim: '12365',
    picture: 'https://picsum.photos/seed/xena/200',
    attendance: { hadir: 15, izin: 0, sakit: 1 },
    exams: { mid1: 87, final1: 90, mid2: 88, final2: 94 },
    proactiveness: { bertanya: 12, menjawab: 7, menambahkan: 4 },
    tasks: { selesai: 9 },
  },
  {
    id: 24,
    name: 'Yudi Setiawan',
    nim: '12366',
    picture: 'https://picsum.photos/seed/yudi/200',
    attendance: { hadir: 11, izin: 2, sakit: 3 },
    exams: { mid1: 68, final1: 71, mid2: 70, final2: 75 },
    proactiveness: { bertanya: 4, menjawab: 1, menambahkan: 0 },
    tasks: { selesai: 7 },
  },
  {
    id: 25,
    name: 'Zahra Aulia',
    nim: '12367',
    picture: 'https://picsum.photos/seed/zahra/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 99, final1: 100, mid2: 98, final2: 100 },
    proactiveness: { bertanya: 17, menjawab: 13, menambahkan: 9 },
    tasks: { selesai: 10 },
  },
  {
    id: 26,
    name: 'Agung Wijaya',
    nim: '12368',
    picture: 'https://picsum.photos/seed/agung/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 85, final1: 89, mid2: 87, final2: 93 },
    proactiveness: { bertanya: 9, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 27,
    name: 'Bella Saphira',
    nim: '12369',
    picture: 'https://picsum.photos/seed/bella/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 92, final1: 95, mid2: 93, final2: 98 },
    proactiveness: { bertanya: 14, menjawab: 9, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 28,
    name: 'Chandra Kirana',
    nim: '12370',
    picture: 'https://picsum.photos/seed/chandra/200',
    attendance: { hadir: 13, izin: 2, sakit: 1 },
    exams: { mid1: 78, final1: 82, mid2: 80, final2: 85 },
    proactiveness: { bertanya: 7, menjawab: 3, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 29,
    name: 'Dinda Ayu',
    nim: '12371',
    picture: 'https://picsum.photos/seed/dinda/200',
    attendance: { hadir: 14, izin: 0, sakit: 2 },
    exams: { mid1: 86, final1: 89, mid2: 87, final2: 91 },
    proactiveness: { bertanya: 10, menjawab: 6, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 30,
    name: 'Erwin Maulana',
    nim: '12372',
    picture: 'https://picsum.photos/seed/erwin/200',
    attendance: { hadir: 12, izin: 1, sakit: 3 },
    exams: { mid1: 73, final1: 76, mid2: 74, final2: 79 },
    proactiveness: { bertanya: 5, menjawab: 2, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 31,
    name: 'Fitriani',
    nim: '12373',
    picture: 'https://picsum.photos/seed/fitriani/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 93, final1: 96, mid2: 94, final2: 99 },
    proactiveness: { bertanya: 13, menjawab: 8, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 32,
    name: 'Gilang Ramadhan',
    nim: '12374',
    picture: 'https://picsum.photos/seed/gilang/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 97, final1: 99, mid2: 96, final2: 100 },
    proactiveness: { bertanya: 16, menjawab: 11, menambahkan: 8 },
    tasks: { selesai: 10 },
  },
  {
    id: 33,
    name: 'Hana Pertiwi',
    nim: '12375',
    picture: 'https://picsum.photos/seed/hana/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 88, final1: 91, mid2: 89, final2: 94 },
    proactiveness: { bertanya: 11, menjawab: 6, menambahkan: 4 },
    tasks: { selesai: 9 },
  },
  {
    id: 34,
    name: 'Ivan Gunawan',
    nim: '12376',
    picture: 'https://picsum.photos/seed/ivan/200',
    attendance: { hadir: 13, izin: 2, sakit: 1 },
    exams: { mid1: 80, final1: 83, mid2: 81, final2: 86 },
    proactiveness: { bertanya: 8, menjawab: 4, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 35,
    name: 'Jihan Nabila',
    nim: '12377',
    picture: 'https://picsum.photos/seed/jihan/200',
    attendance: { hadir: 15, izin: 0, sakit: 1 },
    exams: { mid1: 94, final1: 97, mid2: 95, final2: 100 },
    proactiveness: { bertanya: 14, menjawab: 10, menambahkan: 6 },
    tasks: { selesai: 10 },
  },
];
